name: update-node-versions

on:
  schedule:
    - cron: "30 7 * * 0"
  push:
    branches:
      - main

jobs:
  update-node-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      - run: yarn build
      - uses: ./
      - uses: peter-evans/create-pull-request@v4
        with:
          title: Update Node.js versions
          body: |
            Automated changes by
            [update-node-versions](https://github.com/hongaar/update-node-versions)
            GitHub action
          token: ${{ secrets.GH_PAT }}
